version: '3.8'

services:
  web:
    image: flask
    build:
      context: .
    command:
      - flask
      - run
      - --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./my_flask_app:/app